### PR TITLE
Fix warns

### PR DESCRIPTION
**Pull request by akirak**
Following up to #8, I'm trying to apply obvious fixes.

(I have to create this PR to fire the workflow. Sorry for making the noise.)

### CODE REVIEW

**Comment by akirak** [comment]
There is one `package-lint` error, which is considered more severe than the others:

> 63:54: error: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)

The current default value of `apprentice-key-command-prefix` is `C-c a`, but the key sequence should be left unbound for the user. If I were the author, I wouldn't bind any command in the minor mode map and let the user define keybindings on one's own.

**Comment by akirak** [comment]
@Sasanidas Do you know the use of this code in `apprentice-iex.el`? It's apparently related to comint, but it would be better to not autoload these function overrides because they are not part of the namespace of this package:

```emacs-lisp
(defalias 'run-elixir #'apprentice-iex-run)
(defalias 'inferior-elixir #'apprentice-iex-run)
```

This causes the following error:

>  280:0: error: Aliases should start with the package's prefix "apprentice".

**Comment by akirak** [comment]
I have fixed most of the issues, except for checkdoc warnings. There are quite a few checkdoc warnings due to missing documentation, but some of those warnings may be turned off in the future (https://github.com/melpa/melpa/issues/8450), so I kept them left untouched.

**Comment by Sasanidas** [comment]
> @Sasanidas Do you know the user of this code in `apprentice-iex.el`? It's apparently related to comint, but it would be better to autoload these function overrides because they are not part of the namespace of this package:
> 
> ```emacs-lisp
> (defalias 'run-elixir #'apprentice-iex-run)
> (defalias 'inferior-elixir #'apprentice-iex-run)
> ```
> 
> This causes the following error:
> 
> > 280:0: error: Aliases should start with the package's prefix "apprentice".

I would say it's just a convenience way of using Apprentice , but it can be removed and just add it to the documentation for the user to add in their config.

**Comment by Sasanidas** [comment]
Thanks a lot for the effort! 

So, I'm just concern about the minimum version increase, if you can clarify it, I'll merge the changes and fix the remaining docs and remove the aliases.

Thanks!

**Comment by akirak** [comment]
@Sasanidas Now you can merge this PR. Please also check the comment https://github.com/Sasanidas/Apprentice/pull/10#issuecomment-1507443187.

> So, I'm just concern about the minimum version increase, if you can clarify it, I'll merge the changes and fix the remaining docs and remove the aliases.

It requires Emacs 27.1. This version is already [available on most distributions](https://repology.org/project/emacs/versions), so I think it's fair to depend on it.

I also noticed that this package should no longer depend on `elixir-mode`, since `elixir-ts-mode` is shipped as part of Emacs 29.

Hence the following hook in `apprentice.el` should be removed and added to the documentation instead:

```emacs-lisp
(add-hook 'elixir-mode-hook #'apprentice-mode-hook)
```

**Comment by Sasanidas** [comment]
I see, thanks for the contributions, I'll remove the elixir-mode dependency ASAP, and add the keybindings configuration to the README of the package :+1:

**Pull request merged**
